[package]
name = "zara"
version = "0.1.0"
edition = "2021"
authors = ["Brandon Stansbury <brandonrstansbury@gmail.com"]
description = "An R7RS Scheme Interpreter"
license = "MIT"
repository = "https://github.com/drmonkeysee/Zara"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
